---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

# Load packages and data

```{r setup, include=FALSE}
library(flexdashboard)

library(tidyverse)
library(plotly)
library(p8105.datasets)

data("rest_inspec")
```

Data cleaning

```{r}
rest_inspec <- rest_inspec |>
  janitor::clean_names() |>
  separate(inspection_date, into = c("year", "month", "day"), sep = "-")
  
rest_inspec_filtered <- rest_inspec |>
  filter(year>=2013) |>
  group_by(boro, year) |>
  mutate(average_score = mean(score, na.rm = TRUE))


```

Cleaned names, separated inspection_date variable into day, month, and year, and filtered to only years 2013 and after in order to narrow down the dataset a bit. Also added a variable for average score for each boro each year.

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
rest_inspec_filtered |>
  filter(boro != "Missing") |>
  plot_ly(y = ~score, color = ~ boro, type = "box")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
rest_inspec_filtered |>
  filter(cuisine_description %in% c("American", "Italian", "Korean", "Thai", "Chinese", "Seafood", "Portuguese", "Mediterranean", "Sandwiches", "Spanish", "African", "Irish", "Mexican", "Delicatessen")) |>
    filter(boro != "Missing") |>
  plot_ly(x = ~cuisine_description, color = ~boro, type = "histogram")


```

### Chart C

```{r}
rest_inspec_filtered |>
  filter(boro != "Missing") |>
  plot_ly(x= ~year, y = ~average_score, color= ~boro, type="bar")
```

